# Generated by Django 5.2 on 2025-04-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_regular_user",
        ),
        migrations.AddField(
            model_name="customuser",
            name="organizer_approved",
            field=models.BooleanField(default=False),
        ),
    ]
