# Generated by Django 5.2 on 2025-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_customuser_is_regular_user_organizerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerprofile",
            name="club_category",
            field=models.CharField(default="Academic", max_length=50),
        ),
        migrations.AddField(
            model_name="organizerprofile",
            name="constitution",
            field=models.FileField(blank=True, null=True, upload_to="club_documents/"),
        ),
        migrations.AddField(
            model_name="organizerprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="club_logos/"),
        ),
        migrations.AddField(
            model_name="organizerprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizerprofile",
            name="year_established",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organizerprofile",
            name="club_name",
            field=models.CharField(max_length=200),
        ),
    ]
