# Generated by Django 5.2 on 2025-05-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_organizerprofile_club_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizerprofile",
            name="club_category",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("cultural", "Cultural"),
                    ("sports", "Sports"),
                    ("tech", "Tech and Innovation"),
                    ("literary", "Literary"),
                    ("debate", "Debate and Discussion"),
                    ("social_service", "Social Service"),
                    ("health_fitness", "Health and Fitness"),
                    ("gaming_entertainment", "Gaming and Entertainment"),
                    ("environmental", "Environmental and Sustainability"),
                    ("human_rights", "Human Rights and Social Justice"),
                    ("music", "Music and Arts"),
                    ("film", "Film and Media"),
                    ("photography", "Photography"),
                    ("volunteer", "Volunteer and Outreach"),
                    ("entrepreneurship", "Entrepreneurship and Business"),
                    ("political", "Political and Civic Engagement"),
                    ("spiritual", "Spiritual and Religious"),
                    ("alumni", "Alumni Relations"),
                    ("research", "Research and Development"),
                    ("language_and_culture", "Language and Culture"),
                    ("dance", "Dance and Performance Arts"),
                    ("fashion", "Fashion and Design"),
                    ("writing", "Writing and Literature"),
                    ("theater", "Theater and Drama"),
                    ("sustainability", "Sustainability and Environmental Activism"),
                    ("public_speaking", "Public Speaking and Communication"),
                    ("coding", "Coding and Programming"),
                    ("others", "Others"),
                ],
                default="academic",
                max_length=50,
            ),
        ),
    ]
