# Generated by Django 5.2 on 2025-05-01 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_alter_organizerprofile_club_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_regular_user",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="club_category",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="club_description",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="constitution",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="website",
        ),
        migrations.RemoveField(
            model_name="organizerprofile",
            name="year_established",
        ),
        migrations.AddField(
            model_name="organizerprofile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizerprofile",
            name="club_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organizerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
